services:
  indexer:
    image: snoop
    container_name: indexer
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      snoop
      --database "${DATABASE_URL}"
      --rpc ${RPC_ENDPOINT}
      --batch-size ${BATCH_SIZE-500}
    restart: always
    env_file: "./.env"